name: bench
'on':
  schedule:
    - cron: 0 0 * * *
  push:
    paths:
      - '**.ts'
jobs:
  bare_ABC:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benches
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: ABC
        run: |-
          deno run -A bare.ts &
          sleep 15 && 
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: abc
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main
  bare_DRASH:
    runs-on: ubuntu-latest
    needs:
      - bare_ABC
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benches
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: DRASH
        run: |-
          deno run -A bare.ts &
          sleep 15 && 
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: drash
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main
  bare_OAK:
    runs-on: ubuntu-latest
    needs:
      - bare_ABC
      - bare_DRASH
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benches
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: OAK
        run: |-
          deno run -A bare.ts &
          sleep 15 && 
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: oak
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main
  bare_SERVEST:
    runs-on: ubuntu-latest
    needs:
      - bare_ABC
      - bare_DRASH
      - bare_OAK
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benches
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: SERVEST
        run: |-
          deno run -A bare.ts &
          sleep 15 && 
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: servest
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main
